package messages

import "time"

// CreateTaskRequest is the DTO received from the HTTP layer when creating a task.
// It contains only the fields the client needs to provide -- the rest (ID, timestamps)
// are generated by the system.
type CreateTaskRequest struct {
	Title       string `json:"title" binding:"required"`
	Description string `json:"description"`
}

// TaskResponse is the DTO returned to the client.
// It maps from the domain entity, transforming internal types (like time.Time)
// into a format appropriate for the API consumer.
type TaskResponse struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
